####

BuildDirectory = "../tswow-build"
InstallDirectory = "../tswow-install"

Target.Release.Type = "Release"
Target.Release.CMakeFlags.TrinityCore = "-DTRACY_ENABLE=ON -DTRACY_TIMER_FALLBACK=ON"
Target.Release.Scripts = "dynamic"

Target.RelWithDebInfo.Type = "RelWithDebInfo"
Target.RelWithDebInfo.CMakeFlags.TrinityCore = "-DTRACY_ENABLE=ON -DTRACY_TIMER_FALLBACK=ON"
Target.RelWithDebInfo.Scripts = "dynamic"

Target.Debug.Type = "Debug"
Target.Debug.CMakeFlags.TrinityCore = "-DTRACY_ENABLE=ON -DTRACY_TIMER_FALLBACK=ON -DWITH_COREDEBUG=ON"
Target.Debug.Scripts = "minimal-dynamic"

####